// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_a_Dense_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Weights_address0,
        Weights_ce0,
        Weights_q0,
        Weights_address1,
        Weights_ce1,
        Weights_q1,
        sext_ln9,
        sext_ln9_1,
        sext_ln9_2,
        sext_ln9_3,
        sext_ln9_4,
        sext_ln9_5,
        sext_ln9_6,
        sext_ln9_7,
        sext_ln9_8,
        sext_ln9_9,
        sext_ln9_10,
        sext_ln9_11,
        sext_ln9_12,
        sext_ln9_13,
        sext_ln9_14,
        sext_ln9_15,
        sext_ln9_16,
        sext_ln9_17,
        sext_ln9_18,
        sext_ln9_19,
        sext_ln9_20,
        sext_ln9_21,
        sext_ln9_22,
        sext_ln9_23,
        sext_ln9_24,
        sext_ln9_25,
        sext_ln9_26,
        sext_ln9_27,
        sext_ln9_28,
        sext_ln9_29,
        sext_ln9_30,
        sext_ln9_31,
        OutDense0_address0,
        OutDense0_ce0,
        OutDense0_we0,
        OutDense0_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 17'd1;
parameter    ap_ST_fsm_pp0_stage1 = 17'd2;
parameter    ap_ST_fsm_pp0_stage2 = 17'd4;
parameter    ap_ST_fsm_pp0_stage3 = 17'd8;
parameter    ap_ST_fsm_pp0_stage4 = 17'd16;
parameter    ap_ST_fsm_pp0_stage5 = 17'd32;
parameter    ap_ST_fsm_pp0_stage6 = 17'd64;
parameter    ap_ST_fsm_pp0_stage7 = 17'd128;
parameter    ap_ST_fsm_pp0_stage8 = 17'd256;
parameter    ap_ST_fsm_pp0_stage9 = 17'd512;
parameter    ap_ST_fsm_pp0_stage10 = 17'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 17'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 17'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 17'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 17'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 17'd32768;
parameter    ap_ST_fsm_pp0_stage16 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] Weights_address0;
output   Weights_ce0;
input  [15:0] Weights_q0;
output  [13:0] Weights_address1;
output   Weights_ce1;
input  [15:0] Weights_q1;
input  [11:0] sext_ln9;
input  [11:0] sext_ln9_1;
input  [11:0] sext_ln9_2;
input  [11:0] sext_ln9_3;
input  [11:0] sext_ln9_4;
input  [11:0] sext_ln9_5;
input  [11:0] sext_ln9_6;
input  [11:0] sext_ln9_7;
input  [11:0] sext_ln9_8;
input  [11:0] sext_ln9_9;
input  [11:0] sext_ln9_10;
input  [11:0] sext_ln9_11;
input  [11:0] sext_ln9_12;
input  [11:0] sext_ln9_13;
input  [11:0] sext_ln9_14;
input  [11:0] sext_ln9_15;
input  [11:0] sext_ln9_16;
input  [11:0] sext_ln9_17;
input  [11:0] sext_ln9_18;
input  [11:0] sext_ln9_19;
input  [11:0] sext_ln9_20;
input  [11:0] sext_ln9_21;
input  [11:0] sext_ln9_22;
input  [11:0] sext_ln9_23;
input  [11:0] sext_ln9_24;
input  [11:0] sext_ln9_25;
input  [11:0] sext_ln9_26;
input  [11:0] sext_ln9_27;
input  [11:0] sext_ln9_28;
input  [11:0] sext_ln9_29;
input  [11:0] sext_ln9_30;
input  [11:0] sext_ln9_31;
output  [4:0] OutDense0_address0;
output   OutDense0_ce0;
output   OutDense0_we0;
output  [15:0] OutDense0_d0;

reg ap_idle;
reg[13:0] Weights_address0;
reg Weights_ce0;
reg[13:0] Weights_address1;
reg Weights_ce1;
reg OutDense0_ce0;
reg OutDense0_we0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage16;
wire    ap_block_pp0_stage16_subdone;
reg   [0:0] icmp_ln5_reg_2314;
reg    ap_condition_exit_pp0_iter0_stage16;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg  signed [15:0] reg_666;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_11001;
reg  signed [15:0] reg_671;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_11001;
reg  signed [15:0] reg_676;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
reg  signed [15:0] reg_681;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_11001;
reg  signed [15:0] reg_686;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_11001;
reg  signed [15:0] reg_691;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_11001;
wire  signed [23:0] sext_ln9_31_cast_fu_696_p1;
reg  signed [23:0] sext_ln9_31_cast_reg_2145;
wire    ap_block_pp0_stage0_11001;
wire  signed [23:0] sext_ln9_30_cast_fu_700_p1;
reg  signed [23:0] sext_ln9_30_cast_reg_2150;
wire  signed [23:0] sext_ln9_29_cast_fu_704_p1;
reg  signed [23:0] sext_ln9_29_cast_reg_2155;
wire  signed [23:0] sext_ln9_28_cast_fu_708_p1;
reg  signed [23:0] sext_ln9_28_cast_reg_2160;
wire  signed [23:0] sext_ln9_27_cast_fu_712_p1;
reg  signed [23:0] sext_ln9_27_cast_reg_2165;
wire  signed [23:0] sext_ln9_26_cast_fu_716_p1;
reg  signed [23:0] sext_ln9_26_cast_reg_2170;
wire  signed [23:0] sext_ln9_25_cast_fu_720_p1;
reg  signed [23:0] sext_ln9_25_cast_reg_2175;
wire  signed [23:0] sext_ln9_24_cast_fu_724_p1;
reg  signed [23:0] sext_ln9_24_cast_reg_2180;
wire  signed [23:0] sext_ln9_23_cast_fu_728_p1;
reg  signed [23:0] sext_ln9_23_cast_reg_2185;
wire  signed [23:0] sext_ln9_22_cast_fu_732_p1;
reg  signed [23:0] sext_ln9_22_cast_reg_2190;
wire  signed [23:0] sext_ln9_21_cast_fu_736_p1;
reg  signed [23:0] sext_ln9_21_cast_reg_2195;
wire  signed [23:0] sext_ln9_20_cast_fu_740_p1;
reg  signed [23:0] sext_ln9_20_cast_reg_2200;
wire  signed [23:0] sext_ln9_19_cast_fu_744_p1;
reg  signed [23:0] sext_ln9_19_cast_reg_2205;
wire  signed [23:0] sext_ln9_18_cast_fu_748_p1;
reg  signed [23:0] sext_ln9_18_cast_reg_2210;
wire  signed [23:0] sext_ln9_17_cast_fu_752_p1;
reg  signed [23:0] sext_ln9_17_cast_reg_2215;
wire  signed [23:0] sext_ln9_16_cast_fu_756_p1;
reg  signed [23:0] sext_ln9_16_cast_reg_2220;
wire  signed [23:0] sext_ln9_15_cast_fu_760_p1;
reg  signed [23:0] sext_ln9_15_cast_reg_2225;
wire  signed [23:0] sext_ln9_14_cast_fu_764_p1;
reg  signed [23:0] sext_ln9_14_cast_reg_2230;
wire  signed [23:0] sext_ln9_13_cast_fu_768_p1;
reg  signed [23:0] sext_ln9_13_cast_reg_2235;
wire  signed [23:0] sext_ln9_12_cast_fu_772_p1;
reg  signed [23:0] sext_ln9_12_cast_reg_2240;
wire  signed [23:0] sext_ln9_11_cast_fu_776_p1;
reg  signed [23:0] sext_ln9_11_cast_reg_2245;
wire  signed [23:0] sext_ln9_10_cast_fu_780_p1;
reg  signed [23:0] sext_ln9_10_cast_reg_2250;
wire  signed [23:0] sext_ln9_9_cast_fu_784_p1;
reg  signed [23:0] sext_ln9_9_cast_reg_2255;
wire  signed [23:0] sext_ln9_8_cast_fu_788_p1;
reg  signed [23:0] sext_ln9_8_cast_reg_2260;
wire  signed [23:0] sext_ln9_7_cast_fu_792_p1;
reg  signed [23:0] sext_ln9_7_cast_reg_2265;
wire  signed [23:0] sext_ln9_6_cast_fu_796_p1;
reg  signed [23:0] sext_ln9_6_cast_reg_2270;
wire  signed [23:0] sext_ln9_5_cast_fu_800_p1;
reg  signed [23:0] sext_ln9_5_cast_reg_2275;
wire  signed [23:0] sext_ln9_4_cast_fu_804_p1;
reg  signed [23:0] sext_ln9_4_cast_reg_2280;
wire  signed [23:0] sext_ln9_3_cast_fu_808_p1;
reg  signed [23:0] sext_ln9_3_cast_reg_2285;
wire  signed [23:0] sext_ln9_2_cast_fu_812_p1;
reg  signed [23:0] sext_ln9_2_cast_reg_2290;
wire  signed [23:0] sext_ln9_1_cast_fu_816_p1;
reg  signed [23:0] sext_ln9_1_cast_reg_2295;
wire  signed [23:0] sext_ln9_cast_fu_820_p1;
reg  signed [23:0] sext_ln9_cast_reg_2300;
reg   [4:0] i_2_reg_2305;
reg   [4:0] i_2_reg_2305_pp0_iter1_reg;
wire   [0:0] icmp_ln5_fu_832_p2;
wire   [13:0] zext_ln5_1_fu_844_p1;
reg   [13:0] zext_ln5_1_reg_2318;
reg   [13:0] zext_ln5_1_reg_2318_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] tmp_s_reg_2364;
reg  signed [15:0] Weights_load_35_reg_2504;
reg  signed [15:0] Weights_load_37_reg_2529;
reg  signed [15:0] Weights_load_39_reg_2554;
reg  signed [15:0] Weights_load_41_reg_2579;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_11001;
reg  signed [15:0] Weights_load_42_reg_2604;
reg  signed [15:0] Weights_load_43_reg_2609;
reg  signed [15:0] Weights_load_45_reg_2634;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14_11001;
reg  signed [15:0] Weights_load_46_reg_2659;
reg  signed [15:0] Weights_load_47_reg_2664;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_pp0_stage15_11001;
reg  signed [15:0] Weights_load_48_reg_2689;
reg  signed [15:0] Weights_load_49_reg_2694;
wire    ap_block_pp0_stage16_11001;
reg  signed [15:0] Weights_load_50_reg_2719;
reg  signed [15:0] Weights_load_51_reg_2724;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln9_fu_854_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln9_1_fu_865_p1;
wire   [63:0] zext_ln9_2_fu_903_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln9_3_fu_913_p1;
wire   [63:0] zext_ln9_4_fu_927_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln9_5_fu_939_p1;
wire   [63:0] zext_ln9_6_fu_960_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln9_7_fu_970_p1;
wire   [63:0] zext_ln9_8_fu_1001_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln9_9_fu_1011_p1;
wire   [63:0] zext_ln9_10_fu_1042_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln9_11_fu_1052_p1;
wire   [63:0] zext_ln9_12_fu_1083_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln9_13_fu_1095_p1;
wire   [63:0] zext_ln9_14_fu_1126_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln9_15_fu_1136_p1;
wire   [63:0] zext_ln9_16_fu_1167_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln9_17_fu_1177_p1;
wire   [63:0] zext_ln9_18_fu_1208_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln9_19_fu_1218_p1;
wire   [63:0] zext_ln9_20_fu_1249_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln9_21_fu_1261_p1;
wire   [63:0] zext_ln9_22_fu_1292_p1;
wire    ap_block_pp0_stage11;
wire   [63:0] zext_ln9_23_fu_1302_p1;
wire   [63:0] zext_ln9_24_fu_1333_p1;
wire    ap_block_pp0_stage12;
wire   [63:0] zext_ln9_25_fu_1343_p1;
wire   [63:0] zext_ln9_26_fu_1374_p1;
wire    ap_block_pp0_stage13;
wire   [63:0] zext_ln9_27_fu_1384_p1;
wire   [63:0] zext_ln9_28_fu_1415_p1;
wire    ap_block_pp0_stage14;
wire   [63:0] zext_ln9_29_fu_1427_p1;
wire   [63:0] zext_ln9_30_fu_1457_p1;
wire    ap_block_pp0_stage15;
wire   [63:0] zext_ln9_31_fu_1467_p1;
wire   [63:0] zext_ln11_fu_1835_p1;
wire    ap_block_pp0_stage16;
wire   [63:0] zext_ln5_fu_1840_p1;
reg   [4:0] i_fu_184;
wire   [4:0] add_ln5_fu_838_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_2;
wire   [13:0] add_ln9_fu_848_p2;
wire   [13:0] add_ln9_1_fu_859_p2;
wire  signed [11:0] mul_ln9_fu_879_p1;
wire   [23:0] mul_ln9_fu_879_p2;
wire   [13:0] add_ln9_3_fu_898_p2;
wire   [13:0] add_ln9_5_fu_908_p2;
wire   [13:0] add_ln9_7_fu_922_p2;
wire   [13:0] zext_ln9_5_cast_fu_932_p3;
wire   [13:0] add_ln9_10_fu_955_p2;
wire   [13:0] add_ln9_12_fu_965_p2;
wire  signed [23:0] tmp_19_fu_975_p1;
wire   [23:0] grp_fu_1890_p3;
wire   [15:0] tmp_19_fu_975_p4;
wire   [13:0] add_ln9_14_fu_996_p2;
wire   [13:0] add_ln9_16_fu_1006_p2;
wire  signed [23:0] tmp_20_fu_1016_p1;
wire   [23:0] grp_fu_1898_p3;
wire   [15:0] tmp_20_fu_1016_p4;
wire   [13:0] add_ln9_18_fu_1037_p2;
wire   [13:0] add_ln9_20_fu_1047_p2;
wire  signed [23:0] tmp_21_fu_1057_p1;
wire   [23:0] grp_fu_1906_p3;
wire   [15:0] tmp_21_fu_1057_p4;
wire   [13:0] add_ln9_22_fu_1078_p2;
wire   [13:0] zext_ln9_13_cast_fu_1088_p3;
wire  signed [23:0] tmp_22_fu_1100_p1;
wire   [23:0] grp_fu_1914_p3;
wire   [15:0] tmp_22_fu_1100_p4;
wire   [13:0] add_ln9_25_fu_1121_p2;
wire   [13:0] add_ln9_27_fu_1131_p2;
wire  signed [23:0] tmp_23_fu_1141_p1;
wire   [23:0] grp_fu_1922_p3;
wire   [15:0] tmp_23_fu_1141_p4;
wire   [13:0] add_ln9_29_fu_1162_p2;
wire   [13:0] add_ln9_31_fu_1172_p2;
wire  signed [23:0] tmp_24_fu_1182_p1;
wire   [23:0] grp_fu_1930_p3;
wire   [15:0] tmp_24_fu_1182_p4;
wire   [13:0] add_ln9_33_fu_1203_p2;
wire   [13:0] add_ln9_35_fu_1213_p2;
wire  signed [23:0] tmp_25_fu_1223_p1;
wire   [23:0] grp_fu_1938_p3;
wire   [15:0] tmp_25_fu_1223_p4;
wire   [13:0] add_ln9_37_fu_1244_p2;
wire   [13:0] zext_ln9_21_cast_fu_1254_p3;
wire  signed [23:0] tmp_26_fu_1266_p1;
wire   [23:0] grp_fu_1946_p3;
wire   [15:0] tmp_26_fu_1266_p4;
wire   [13:0] add_ln9_40_fu_1287_p2;
wire   [13:0] add_ln9_42_fu_1297_p2;
wire  signed [23:0] tmp_27_fu_1307_p1;
wire   [23:0] grp_fu_1954_p3;
wire   [15:0] tmp_27_fu_1307_p4;
wire   [13:0] add_ln9_44_fu_1328_p2;
wire   [13:0] add_ln9_46_fu_1338_p2;
wire  signed [23:0] tmp_28_fu_1348_p1;
wire   [23:0] grp_fu_1962_p3;
wire   [15:0] tmp_28_fu_1348_p4;
wire   [13:0] add_ln9_48_fu_1369_p2;
wire   [13:0] add_ln9_50_fu_1379_p2;
wire  signed [23:0] tmp_29_fu_1389_p1;
wire   [23:0] grp_fu_1970_p3;
wire   [15:0] tmp_29_fu_1389_p4;
wire   [13:0] add_ln9_52_fu_1410_p2;
wire   [13:0] zext_ln9_29_cast_fu_1420_p3;
wire  signed [23:0] tmp_30_fu_1432_p1;
wire   [23:0] grp_fu_1978_p3;
wire   [15:0] tmp_30_fu_1432_p4;
wire   [13:0] add_ln9_55_fu_1452_p2;
wire   [13:0] add_ln9_57_fu_1462_p2;
wire  signed [23:0] tmp_31_fu_1472_p1;
wire   [23:0] grp_fu_1986_p3;
wire   [15:0] tmp_31_fu_1472_p4;
wire  signed [23:0] tmp_32_fu_1493_p1;
wire   [23:0] grp_fu_1994_p3;
wire   [15:0] tmp_32_fu_1493_p4;
wire  signed [23:0] tmp_33_fu_1513_p1;
wire   [23:0] grp_fu_2002_p3;
wire   [15:0] tmp_33_fu_1513_p4;
wire  signed [23:0] tmp_34_fu_1534_p1;
wire   [23:0] grp_fu_2010_p3;
wire   [15:0] tmp_34_fu_1534_p4;
wire  signed [23:0] tmp_35_fu_1554_p1;
wire   [23:0] grp_fu_2018_p3;
wire   [15:0] tmp_35_fu_1554_p4;
wire  signed [23:0] tmp_36_fu_1575_p1;
wire   [23:0] grp_fu_2026_p3;
wire   [15:0] tmp_36_fu_1575_p4;
wire  signed [23:0] tmp_37_fu_1595_p1;
wire   [23:0] grp_fu_2034_p3;
wire   [15:0] tmp_37_fu_1595_p4;
wire  signed [23:0] tmp_38_fu_1615_p1;
wire   [23:0] grp_fu_2042_p3;
wire   [15:0] tmp_38_fu_1615_p4;
wire  signed [23:0] tmp_39_fu_1635_p1;
wire   [23:0] grp_fu_2050_p3;
wire   [15:0] tmp_39_fu_1635_p4;
wire  signed [23:0] tmp_40_fu_1656_p1;
wire   [23:0] grp_fu_2058_p3;
wire   [15:0] tmp_40_fu_1656_p4;
wire  signed [23:0] tmp_41_fu_1676_p1;
wire   [23:0] grp_fu_2066_p3;
wire   [15:0] tmp_41_fu_1676_p4;
wire  signed [23:0] tmp_42_fu_1696_p1;
wire   [23:0] grp_fu_2074_p3;
wire   [15:0] tmp_42_fu_1696_p4;
wire  signed [23:0] tmp_43_fu_1716_p1;
wire   [23:0] grp_fu_2082_p3;
wire   [15:0] tmp_43_fu_1716_p4;
wire  signed [23:0] tmp_44_fu_1736_p1;
wire   [23:0] grp_fu_2090_p3;
wire   [15:0] tmp_44_fu_1736_p4;
wire  signed [23:0] tmp_45_fu_1756_p1;
wire   [23:0] grp_fu_2098_p3;
wire   [15:0] tmp_45_fu_1756_p4;
wire  signed [23:0] tmp_46_fu_1776_p1;
wire   [23:0] grp_fu_2106_p3;
wire   [15:0] tmp_46_fu_1776_p4;
wire  signed [23:0] tmp_47_fu_1796_p1;
wire   [23:0] grp_fu_2114_p3;
wire   [15:0] tmp_47_fu_1796_p4;
wire  signed [23:0] tmp_48_fu_1813_p1;
wire   [23:0] grp_fu_2122_p3;
wire   [15:0] tmp_48_fu_1813_p4;
wire   [13:0] add_ln11_fu_1830_p2;
wire  signed [23:0] s_fu_1844_p1;
wire   [23:0] grp_fu_2130_p3;
wire  signed [15:0] s_fu_1844_p4;
wire  signed [15:0] sext_ln11_1_fu_1857_p0;
wire  signed [15:0] add_ln11_2_fu_1861_p1;
wire  signed [16:0] sext_ln11_fu_1853_p1;
wire  signed [16:0] sext_ln11_1_fu_1857_p1;
wire   [16:0] add_ln11_1_fu_1867_p2;
wire   [0:0] tmp_fu_1873_p3;
wire   [15:0] add_ln11_2_fu_1861_p2;
wire  signed [11:0] grp_fu_1890_p1;
wire   [23:0] grp_fu_1890_p2;
wire  signed [11:0] grp_fu_1898_p1;
wire   [23:0] grp_fu_1898_p2;
wire  signed [11:0] grp_fu_1906_p1;
wire   [23:0] grp_fu_1906_p2;
wire  signed [11:0] grp_fu_1914_p1;
wire   [23:0] grp_fu_1914_p2;
wire  signed [11:0] grp_fu_1922_p1;
wire   [23:0] grp_fu_1922_p2;
wire  signed [11:0] grp_fu_1930_p1;
wire   [23:0] grp_fu_1930_p2;
wire  signed [11:0] grp_fu_1938_p1;
wire   [23:0] grp_fu_1938_p2;
wire  signed [11:0] grp_fu_1946_p1;
wire   [23:0] grp_fu_1946_p2;
wire  signed [11:0] grp_fu_1954_p1;
wire   [23:0] grp_fu_1954_p2;
wire  signed [11:0] grp_fu_1962_p1;
wire   [23:0] grp_fu_1962_p2;
wire  signed [11:0] grp_fu_1970_p1;
wire   [23:0] grp_fu_1970_p2;
wire  signed [11:0] grp_fu_1978_p1;
wire   [23:0] grp_fu_1978_p2;
wire  signed [11:0] grp_fu_1986_p1;
wire   [23:0] grp_fu_1986_p2;
wire  signed [11:0] grp_fu_1994_p1;
wire   [23:0] grp_fu_1994_p2;
wire  signed [11:0] grp_fu_2002_p1;
wire   [23:0] grp_fu_2002_p2;
wire  signed [11:0] grp_fu_2010_p1;
wire   [23:0] grp_fu_2010_p2;
wire  signed [11:0] grp_fu_2018_p1;
wire   [23:0] grp_fu_2018_p2;
wire  signed [11:0] grp_fu_2026_p1;
wire   [23:0] grp_fu_2026_p2;
wire  signed [11:0] grp_fu_2034_p1;
wire   [23:0] grp_fu_2034_p2;
wire  signed [11:0] grp_fu_2042_p1;
wire   [23:0] grp_fu_2042_p2;
wire  signed [11:0] grp_fu_2050_p1;
wire   [23:0] grp_fu_2050_p2;
wire  signed [11:0] grp_fu_2058_p1;
wire   [23:0] grp_fu_2058_p2;
wire  signed [11:0] grp_fu_2066_p1;
wire   [23:0] grp_fu_2066_p2;
wire  signed [11:0] grp_fu_2074_p1;
wire   [23:0] grp_fu_2074_p2;
wire  signed [11:0] grp_fu_2082_p1;
wire   [23:0] grp_fu_2082_p2;
wire  signed [11:0] grp_fu_2090_p1;
wire   [23:0] grp_fu_2090_p2;
wire  signed [11:0] grp_fu_2098_p1;
wire   [23:0] grp_fu_2098_p2;
wire  signed [11:0] grp_fu_2106_p1;
wire   [23:0] grp_fu_2106_p2;
wire  signed [11:0] grp_fu_2114_p1;
wire   [23:0] grp_fu_2114_p2;
wire  signed [11:0] grp_fu_2122_p1;
wire   [23:0] grp_fu_2122_p2;
wire  signed [11:0] grp_fu_2130_p1;
wire   [23:0] grp_fu_2130_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [16:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
wire    ap_block_pp0_stage15_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_184 = 5'd0;
#0 ap_done_reg = 1'b0;
end

CNN_mul_16s_12s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
mul_16s_12s_24_1_1_U222(
    .din0(Weights_q1),
    .din1(mul_ln9_fu_879_p1),
    .dout(mul_ln9_fu_879_p2)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U223(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_q0),
    .din1(grp_fu_1890_p1),
    .din2(grp_fu_1890_p2),
    .ce(1'b1),
    .dout(grp_fu_1890_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U224(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_q1),
    .din1(grp_fu_1898_p1),
    .din2(grp_fu_1898_p2),
    .ce(1'b1),
    .dout(grp_fu_1898_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U225(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_666),
    .din1(grp_fu_1906_p1),
    .din2(grp_fu_1906_p2),
    .ce(1'b1),
    .dout(grp_fu_1906_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U226(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_666),
    .din1(grp_fu_1914_p1),
    .din2(grp_fu_1914_p2),
    .ce(1'b1),
    .dout(grp_fu_1914_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U227(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_671),
    .din1(grp_fu_1922_p1),
    .din2(grp_fu_1922_p2),
    .ce(1'b1),
    .dout(grp_fu_1922_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U228(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_666),
    .din1(grp_fu_1930_p1),
    .din2(grp_fu_1930_p2),
    .ce(1'b1),
    .dout(grp_fu_1930_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U229(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_676),
    .din1(grp_fu_1938_p1),
    .din2(grp_fu_1938_p2),
    .ce(1'b1),
    .dout(grp_fu_1938_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U230(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_671),
    .din1(grp_fu_1946_p1),
    .din2(grp_fu_1946_p2),
    .ce(1'b1),
    .dout(grp_fu_1946_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U231(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_681),
    .din1(grp_fu_1954_p1),
    .din2(grp_fu_1954_p2),
    .ce(1'b1),
    .dout(grp_fu_1954_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U232(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_666),
    .din1(grp_fu_1962_p1),
    .din2(grp_fu_1962_p2),
    .ce(1'b1),
    .dout(grp_fu_1962_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U233(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_686),
    .din1(grp_fu_1970_p1),
    .din2(grp_fu_1970_p2),
    .ce(1'b1),
    .dout(grp_fu_1970_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U234(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_676),
    .din1(grp_fu_1978_p1),
    .din2(grp_fu_1978_p2),
    .ce(1'b1),
    .dout(grp_fu_1978_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U235(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_691),
    .din1(grp_fu_1986_p1),
    .din2(grp_fu_1986_p2),
    .ce(1'b1),
    .dout(grp_fu_1986_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U236(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_671),
    .din1(grp_fu_1994_p1),
    .din2(grp_fu_1994_p2),
    .ce(1'b1),
    .dout(grp_fu_1994_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U237(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_35_reg_2504),
    .din1(grp_fu_2002_p1),
    .din2(grp_fu_2002_p2),
    .ce(1'b1),
    .dout(grp_fu_2002_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U238(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_681),
    .din1(grp_fu_2010_p1),
    .din2(grp_fu_2010_p2),
    .ce(1'b1),
    .dout(grp_fu_2010_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U239(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_37_reg_2529),
    .din1(grp_fu_2018_p1),
    .din2(grp_fu_2018_p2),
    .ce(1'b1),
    .dout(grp_fu_2018_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U240(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_666),
    .din1(grp_fu_2026_p1),
    .din2(grp_fu_2026_p2),
    .ce(1'b1),
    .dout(grp_fu_2026_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U241(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_39_reg_2554),
    .din1(grp_fu_2034_p1),
    .din2(grp_fu_2034_p2),
    .ce(1'b1),
    .dout(grp_fu_2034_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U242(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_686),
    .din1(grp_fu_2042_p1),
    .din2(grp_fu_2042_p2),
    .ce(1'b1),
    .dout(grp_fu_2042_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U243(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_41_reg_2579),
    .din1(grp_fu_2050_p1),
    .din2(grp_fu_2050_p2),
    .ce(1'b1),
    .dout(grp_fu_2050_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U244(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_42_reg_2604),
    .din1(grp_fu_2058_p1),
    .din2(grp_fu_2058_p2),
    .ce(1'b1),
    .dout(grp_fu_2058_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U245(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_43_reg_2609),
    .din1(grp_fu_2066_p1),
    .din2(grp_fu_2066_p2),
    .ce(1'b1),
    .dout(grp_fu_2066_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U246(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_691),
    .din1(grp_fu_2074_p1),
    .din2(grp_fu_2074_p2),
    .ce(1'b1),
    .dout(grp_fu_2074_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U247(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_45_reg_2634),
    .din1(grp_fu_2082_p1),
    .din2(grp_fu_2082_p2),
    .ce(1'b1),
    .dout(grp_fu_2082_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U248(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_46_reg_2659),
    .din1(grp_fu_2090_p1),
    .din2(grp_fu_2090_p2),
    .ce(1'b1),
    .dout(grp_fu_2090_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U249(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_47_reg_2664),
    .din1(grp_fu_2098_p1),
    .din2(grp_fu_2098_p2),
    .ce(1'b1),
    .dout(grp_fu_2098_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U250(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_48_reg_2689),
    .din1(grp_fu_2106_p1),
    .din2(grp_fu_2106_p2),
    .ce(1'b1),
    .dout(grp_fu_2106_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U251(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_49_reg_2694),
    .din1(grp_fu_2114_p1),
    .din2(grp_fu_2114_p2),
    .ce(1'b1),
    .dout(grp_fu_2114_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U252(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_50_reg_2719),
    .din1(grp_fu_2122_p1),
    .din2(grp_fu_2122_p2),
    .ce(1'b1),
    .dout(grp_fu_2122_p3)
);

CNN_mac_muladd_16s_12s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_12s_24ns_24_4_1_U253(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_51_reg_2724),
    .din1(grp_fu_2130_p1),
    .din2(grp_fu_2130_p2),
    .ce(1'b1),
    .dout(grp_fu_2130_p3)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage16),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage16)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln5_fu_832_p2 == 1'd0))) begin
            i_fu_184 <= add_ln5_fu_838_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_184 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_666 <= Weights_q1;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_666 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_671 <= Weights_q1;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_671 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            reg_676 <= Weights_q1;
        end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            reg_676 <= Weights_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            reg_681 <= Weights_q1;
        end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            reg_681 <= Weights_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
            reg_686 <= Weights_q1;
        end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            reg_686 <= Weights_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
            reg_691 <= Weights_q1;
        end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            reg_691 <= Weights_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        Weights_load_35_reg_2504 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        Weights_load_37_reg_2529 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        Weights_load_39_reg_2554 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        Weights_load_41_reg_2579 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        Weights_load_42_reg_2604 <= Weights_q1;
        Weights_load_43_reg_2609 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        Weights_load_45_reg_2634 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        Weights_load_46_reg_2659 <= Weights_q1;
        Weights_load_47_reg_2664 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        Weights_load_48_reg_2689 <= Weights_q1;
        Weights_load_49_reg_2694 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        Weights_load_50_reg_2719 <= Weights_q1;
        Weights_load_51_reg_2724 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_2305 <= ap_sig_allocacmp_i_2;
        i_2_reg_2305_pp0_iter1_reg <= i_2_reg_2305;
        icmp_ln5_reg_2314 <= icmp_ln5_fu_832_p2;
        sext_ln9_10_cast_reg_2250 <= sext_ln9_10_cast_fu_780_p1;
        sext_ln9_11_cast_reg_2245 <= sext_ln9_11_cast_fu_776_p1;
        sext_ln9_12_cast_reg_2240 <= sext_ln9_12_cast_fu_772_p1;
        sext_ln9_13_cast_reg_2235 <= sext_ln9_13_cast_fu_768_p1;
        sext_ln9_14_cast_reg_2230 <= sext_ln9_14_cast_fu_764_p1;
        sext_ln9_15_cast_reg_2225 <= sext_ln9_15_cast_fu_760_p1;
        sext_ln9_16_cast_reg_2220 <= sext_ln9_16_cast_fu_756_p1;
        sext_ln9_17_cast_reg_2215 <= sext_ln9_17_cast_fu_752_p1;
        sext_ln9_18_cast_reg_2210 <= sext_ln9_18_cast_fu_748_p1;
        sext_ln9_19_cast_reg_2205 <= sext_ln9_19_cast_fu_744_p1;
        sext_ln9_1_cast_reg_2295 <= sext_ln9_1_cast_fu_816_p1;
        sext_ln9_20_cast_reg_2200 <= sext_ln9_20_cast_fu_740_p1;
        sext_ln9_21_cast_reg_2195 <= sext_ln9_21_cast_fu_736_p1;
        sext_ln9_22_cast_reg_2190 <= sext_ln9_22_cast_fu_732_p1;
        sext_ln9_23_cast_reg_2185 <= sext_ln9_23_cast_fu_728_p1;
        sext_ln9_24_cast_reg_2180 <= sext_ln9_24_cast_fu_724_p1;
        sext_ln9_25_cast_reg_2175 <= sext_ln9_25_cast_fu_720_p1;
        sext_ln9_26_cast_reg_2170 <= sext_ln9_26_cast_fu_716_p1;
        sext_ln9_27_cast_reg_2165 <= sext_ln9_27_cast_fu_712_p1;
        sext_ln9_28_cast_reg_2160 <= sext_ln9_28_cast_fu_708_p1;
        sext_ln9_29_cast_reg_2155 <= sext_ln9_29_cast_fu_704_p1;
        sext_ln9_2_cast_reg_2290 <= sext_ln9_2_cast_fu_812_p1;
        sext_ln9_30_cast_reg_2150 <= sext_ln9_30_cast_fu_700_p1;
        sext_ln9_31_cast_reg_2145 <= sext_ln9_31_cast_fu_696_p1;
        sext_ln9_3_cast_reg_2285 <= sext_ln9_3_cast_fu_808_p1;
        sext_ln9_4_cast_reg_2280 <= sext_ln9_4_cast_fu_804_p1;
        sext_ln9_5_cast_reg_2275 <= sext_ln9_5_cast_fu_800_p1;
        sext_ln9_6_cast_reg_2270 <= sext_ln9_6_cast_fu_796_p1;
        sext_ln9_7_cast_reg_2265 <= sext_ln9_7_cast_fu_792_p1;
        sext_ln9_8_cast_reg_2260 <= sext_ln9_8_cast_fu_788_p1;
        sext_ln9_9_cast_reg_2255 <= sext_ln9_9_cast_fu_784_p1;
        sext_ln9_cast_reg_2300 <= sext_ln9_cast_fu_820_p1;
        zext_ln5_1_reg_2318[4 : 0] <= zext_ln5_1_fu_844_p1[4 : 0];
        zext_ln5_1_reg_2318_pp0_iter1_reg[4 : 0] <= zext_ln5_1_reg_2318[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_s_reg_2364 <= {{mul_ln9_fu_879_p2[23:8]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutDense0_ce0 = 1'b1;
    end else begin
        OutDense0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutDense0_we0 = 1'b1;
    end else begin
        OutDense0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        Weights_address0 = zext_ln11_fu_1835_p1;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        Weights_address0 = zext_ln9_31_fu_1467_p1;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        Weights_address0 = zext_ln9_29_fu_1427_p1;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        Weights_address0 = zext_ln9_27_fu_1384_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        Weights_address0 = zext_ln9_25_fu_1343_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        Weights_address0 = zext_ln9_23_fu_1302_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        Weights_address0 = zext_ln9_21_fu_1261_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        Weights_address0 = zext_ln9_19_fu_1218_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        Weights_address0 = zext_ln9_17_fu_1177_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        Weights_address0 = zext_ln9_15_fu_1136_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        Weights_address0 = zext_ln9_13_fu_1095_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        Weights_address0 = zext_ln9_11_fu_1052_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        Weights_address0 = zext_ln9_9_fu_1011_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        Weights_address0 = zext_ln9_7_fu_970_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Weights_address0 = zext_ln9_5_fu_939_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Weights_address0 = zext_ln9_3_fu_913_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Weights_address0 = zext_ln9_1_fu_865_p1;
    end else begin
        Weights_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            Weights_address1 = zext_ln9_30_fu_1457_p1;
        end else if (((1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
            Weights_address1 = zext_ln9_28_fu_1415_p1;
        end else if (((1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
            Weights_address1 = zext_ln9_26_fu_1374_p1;
        end else if (((1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            Weights_address1 = zext_ln9_24_fu_1333_p1;
        end else if (((1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
            Weights_address1 = zext_ln9_22_fu_1292_p1;
        end else if (((1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            Weights_address1 = zext_ln9_20_fu_1249_p1;
        end else if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            Weights_address1 = zext_ln9_18_fu_1208_p1;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            Weights_address1 = zext_ln9_16_fu_1167_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            Weights_address1 = zext_ln9_14_fu_1126_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            Weights_address1 = zext_ln9_12_fu_1083_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            Weights_address1 = zext_ln9_10_fu_1042_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            Weights_address1 = zext_ln9_8_fu_1001_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            Weights_address1 = zext_ln9_6_fu_960_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            Weights_address1 = zext_ln9_4_fu_927_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Weights_address1 = zext_ln9_2_fu_903_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Weights_address1 = zext_ln9_fu_854_p1;
        end else begin
            Weights_address1 = 'bx;
        end
    end else begin
        Weights_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage7_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Weights_ce0 = 1'b1;
    end else begin
        Weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage8_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Weights_ce1 = 1'b1;
    end else begin
        Weights_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5_reg_2314 == 1'd1) & (1'b0 == ap_block_pp0_stage16_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_condition_exit_pp0_iter0_stage16 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage16 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5_reg_2314 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage16_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_184;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_pp0_stage16 : begin
            if ((1'b0 == ap_block_pp0_stage16_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutDense0_address0 = zext_ln5_fu_1840_p1;

assign OutDense0_d0 = ((tmp_fu_1873_p3[0:0] == 1'b1) ? 16'd0 : add_ln11_2_fu_1861_p2);

assign add_ln11_1_fu_1867_p2 = ($signed(sext_ln11_fu_1853_p1) + $signed(sext_ln11_1_fu_1857_p1));

assign add_ln11_2_fu_1861_p1 = Weights_q0;

assign add_ln11_2_fu_1861_p2 = ($signed(s_fu_1844_p4) + $signed(add_ln11_2_fu_1861_p1));

assign add_ln11_fu_1830_p2 = ($signed(zext_ln5_1_reg_2318_pp0_iter1_reg) + $signed(14'd10940));

assign add_ln5_fu_838_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign add_ln9_10_fu_955_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10420));

assign add_ln9_12_fu_965_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10440));

assign add_ln9_14_fu_996_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10460));

assign add_ln9_16_fu_1006_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10480));

assign add_ln9_18_fu_1037_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10500));

assign add_ln9_1_fu_859_p2 = ($signed(zext_ln5_1_fu_844_p1) + $signed(14'd10320));

assign add_ln9_20_fu_1047_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10520));

assign add_ln9_22_fu_1078_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10540));

assign add_ln9_25_fu_1121_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10580));

assign add_ln9_27_fu_1131_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10600));

assign add_ln9_29_fu_1162_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10620));

assign add_ln9_31_fu_1172_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10640));

assign add_ln9_33_fu_1203_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10660));

assign add_ln9_35_fu_1213_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10680));

assign add_ln9_37_fu_1244_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10700));

assign add_ln9_3_fu_898_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10340));

assign add_ln9_40_fu_1287_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10740));

assign add_ln9_42_fu_1297_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10760));

assign add_ln9_44_fu_1328_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10780));

assign add_ln9_46_fu_1338_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10800));

assign add_ln9_48_fu_1369_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10820));

assign add_ln9_50_fu_1379_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10840));

assign add_ln9_52_fu_1410_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10860));

assign add_ln9_55_fu_1452_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10900));

assign add_ln9_57_fu_1462_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10920));

assign add_ln9_5_fu_908_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10360));

assign add_ln9_7_fu_922_p2 = ($signed(zext_ln5_1_reg_2318) + $signed(14'd10380));

assign add_ln9_fu_848_p2 = ($signed(zext_ln5_1_fu_844_p1) + $signed(14'd10300));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage16 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage16;

assign grp_fu_1890_p1 = sext_ln9_1_cast_reg_2295;

assign grp_fu_1890_p2 = {{tmp_s_reg_2364}, {8'd0}};

assign grp_fu_1898_p1 = sext_ln9_2_cast_reg_2290;

assign grp_fu_1898_p2 = {{tmp_19_fu_975_p4}, {8'd0}};

assign grp_fu_1906_p1 = sext_ln9_3_cast_reg_2285;

assign grp_fu_1906_p2 = {{tmp_20_fu_1016_p4}, {8'd0}};

assign grp_fu_1914_p1 = sext_ln9_4_cast_reg_2280;

assign grp_fu_1914_p2 = {{tmp_21_fu_1057_p4}, {8'd0}};

assign grp_fu_1922_p1 = sext_ln9_5_cast_reg_2275;

assign grp_fu_1922_p2 = {{tmp_22_fu_1100_p4}, {8'd0}};

assign grp_fu_1930_p1 = sext_ln9_6_cast_reg_2270;

assign grp_fu_1930_p2 = {{tmp_23_fu_1141_p4}, {8'd0}};

assign grp_fu_1938_p1 = sext_ln9_7_cast_reg_2265;

assign grp_fu_1938_p2 = {{tmp_24_fu_1182_p4}, {8'd0}};

assign grp_fu_1946_p1 = sext_ln9_8_cast_reg_2260;

assign grp_fu_1946_p2 = {{tmp_25_fu_1223_p4}, {8'd0}};

assign grp_fu_1954_p1 = sext_ln9_9_cast_reg_2255;

assign grp_fu_1954_p2 = {{tmp_26_fu_1266_p4}, {8'd0}};

assign grp_fu_1962_p1 = sext_ln9_10_cast_reg_2250;

assign grp_fu_1962_p2 = {{tmp_27_fu_1307_p4}, {8'd0}};

assign grp_fu_1970_p1 = sext_ln9_11_cast_reg_2245;

assign grp_fu_1970_p2 = {{tmp_28_fu_1348_p4}, {8'd0}};

assign grp_fu_1978_p1 = sext_ln9_12_cast_reg_2240;

assign grp_fu_1978_p2 = {{tmp_29_fu_1389_p4}, {8'd0}};

assign grp_fu_1986_p1 = sext_ln9_13_cast_reg_2235;

assign grp_fu_1986_p2 = {{tmp_30_fu_1432_p4}, {8'd0}};

assign grp_fu_1994_p1 = sext_ln9_14_cast_reg_2230;

assign grp_fu_1994_p2 = {{tmp_31_fu_1472_p4}, {8'd0}};

assign grp_fu_2002_p1 = sext_ln9_15_cast_reg_2225;

assign grp_fu_2002_p2 = {{tmp_32_fu_1493_p4}, {8'd0}};

assign grp_fu_2010_p1 = sext_ln9_16_cast_reg_2220;

assign grp_fu_2010_p2 = {{tmp_33_fu_1513_p4}, {8'd0}};

assign grp_fu_2018_p1 = sext_ln9_17_cast_reg_2215;

assign grp_fu_2018_p2 = {{tmp_34_fu_1534_p4}, {8'd0}};

assign grp_fu_2026_p1 = sext_ln9_18_cast_reg_2210;

assign grp_fu_2026_p2 = {{tmp_35_fu_1554_p4}, {8'd0}};

assign grp_fu_2034_p1 = sext_ln9_19_cast_reg_2205;

assign grp_fu_2034_p2 = {{tmp_36_fu_1575_p4}, {8'd0}};

assign grp_fu_2042_p1 = sext_ln9_20_cast_reg_2200;

assign grp_fu_2042_p2 = {{tmp_37_fu_1595_p4}, {8'd0}};

assign grp_fu_2050_p1 = sext_ln9_21_cast_reg_2195;

assign grp_fu_2050_p2 = {{tmp_38_fu_1615_p4}, {8'd0}};

assign grp_fu_2058_p1 = sext_ln9_22_cast_reg_2190;

assign grp_fu_2058_p2 = {{tmp_39_fu_1635_p4}, {8'd0}};

assign grp_fu_2066_p1 = sext_ln9_23_cast_reg_2185;

assign grp_fu_2066_p2 = {{tmp_40_fu_1656_p4}, {8'd0}};

assign grp_fu_2074_p1 = sext_ln9_24_cast_reg_2180;

assign grp_fu_2074_p2 = {{tmp_41_fu_1676_p4}, {8'd0}};

assign grp_fu_2082_p1 = sext_ln9_25_cast_reg_2175;

assign grp_fu_2082_p2 = {{tmp_42_fu_1696_p4}, {8'd0}};

assign grp_fu_2090_p1 = sext_ln9_26_cast_reg_2170;

assign grp_fu_2090_p2 = {{tmp_43_fu_1716_p4}, {8'd0}};

assign grp_fu_2098_p1 = sext_ln9_27_cast_reg_2165;

assign grp_fu_2098_p2 = {{tmp_44_fu_1736_p4}, {8'd0}};

assign grp_fu_2106_p1 = sext_ln9_28_cast_reg_2160;

assign grp_fu_2106_p2 = {{tmp_45_fu_1756_p4}, {8'd0}};

assign grp_fu_2114_p1 = sext_ln9_29_cast_reg_2155;

assign grp_fu_2114_p2 = {{tmp_46_fu_1776_p4}, {8'd0}};

assign grp_fu_2122_p1 = sext_ln9_30_cast_reg_2150;

assign grp_fu_2122_p2 = {{tmp_47_fu_1796_p4}, {8'd0}};

assign grp_fu_2130_p1 = sext_ln9_31_cast_reg_2145;

assign grp_fu_2130_p2 = {{tmp_48_fu_1813_p4}, {8'd0}};

assign icmp_ln5_fu_832_p2 = ((ap_sig_allocacmp_i_2 == 5'd20) ? 1'b1 : 1'b0);

assign mul_ln9_fu_879_p1 = sext_ln9_cast_reg_2300;

assign s_fu_1844_p1 = grp_fu_2130_p3;

assign s_fu_1844_p4 = {{s_fu_1844_p1[23:8]}};

assign sext_ln11_1_fu_1857_p0 = Weights_q0;

assign sext_ln11_1_fu_1857_p1 = sext_ln11_1_fu_1857_p0;

assign sext_ln11_fu_1853_p1 = s_fu_1844_p4;

assign sext_ln9_10_cast_fu_780_p1 = $signed(sext_ln9_10);

assign sext_ln9_11_cast_fu_776_p1 = $signed(sext_ln9_11);

assign sext_ln9_12_cast_fu_772_p1 = $signed(sext_ln9_12);

assign sext_ln9_13_cast_fu_768_p1 = $signed(sext_ln9_13);

assign sext_ln9_14_cast_fu_764_p1 = $signed(sext_ln9_14);

assign sext_ln9_15_cast_fu_760_p1 = $signed(sext_ln9_15);

assign sext_ln9_16_cast_fu_756_p1 = $signed(sext_ln9_16);

assign sext_ln9_17_cast_fu_752_p1 = $signed(sext_ln9_17);

assign sext_ln9_18_cast_fu_748_p1 = $signed(sext_ln9_18);

assign sext_ln9_19_cast_fu_744_p1 = $signed(sext_ln9_19);

assign sext_ln9_1_cast_fu_816_p1 = $signed(sext_ln9_1);

assign sext_ln9_20_cast_fu_740_p1 = $signed(sext_ln9_20);

assign sext_ln9_21_cast_fu_736_p1 = $signed(sext_ln9_21);

assign sext_ln9_22_cast_fu_732_p1 = $signed(sext_ln9_22);

assign sext_ln9_23_cast_fu_728_p1 = $signed(sext_ln9_23);

assign sext_ln9_24_cast_fu_724_p1 = $signed(sext_ln9_24);

assign sext_ln9_25_cast_fu_720_p1 = $signed(sext_ln9_25);

assign sext_ln9_26_cast_fu_716_p1 = $signed(sext_ln9_26);

assign sext_ln9_27_cast_fu_712_p1 = $signed(sext_ln9_27);

assign sext_ln9_28_cast_fu_708_p1 = $signed(sext_ln9_28);

assign sext_ln9_29_cast_fu_704_p1 = $signed(sext_ln9_29);

assign sext_ln9_2_cast_fu_812_p1 = $signed(sext_ln9_2);

assign sext_ln9_30_cast_fu_700_p1 = $signed(sext_ln9_30);

assign sext_ln9_31_cast_fu_696_p1 = $signed(sext_ln9_31);

assign sext_ln9_3_cast_fu_808_p1 = $signed(sext_ln9_3);

assign sext_ln9_4_cast_fu_804_p1 = $signed(sext_ln9_4);

assign sext_ln9_5_cast_fu_800_p1 = $signed(sext_ln9_5);

assign sext_ln9_6_cast_fu_796_p1 = $signed(sext_ln9_6);

assign sext_ln9_7_cast_fu_792_p1 = $signed(sext_ln9_7);

assign sext_ln9_8_cast_fu_788_p1 = $signed(sext_ln9_8);

assign sext_ln9_9_cast_fu_784_p1 = $signed(sext_ln9_9);

assign sext_ln9_cast_fu_820_p1 = $signed(sext_ln9);

assign tmp_19_fu_975_p1 = grp_fu_1890_p3;

assign tmp_19_fu_975_p4 = {{tmp_19_fu_975_p1[23:8]}};

assign tmp_20_fu_1016_p1 = grp_fu_1898_p3;

assign tmp_20_fu_1016_p4 = {{tmp_20_fu_1016_p1[23:8]}};

assign tmp_21_fu_1057_p1 = grp_fu_1906_p3;

assign tmp_21_fu_1057_p4 = {{tmp_21_fu_1057_p1[23:8]}};

assign tmp_22_fu_1100_p1 = grp_fu_1914_p3;

assign tmp_22_fu_1100_p4 = {{tmp_22_fu_1100_p1[23:8]}};

assign tmp_23_fu_1141_p1 = grp_fu_1922_p3;

assign tmp_23_fu_1141_p4 = {{tmp_23_fu_1141_p1[23:8]}};

assign tmp_24_fu_1182_p1 = grp_fu_1930_p3;

assign tmp_24_fu_1182_p4 = {{tmp_24_fu_1182_p1[23:8]}};

assign tmp_25_fu_1223_p1 = grp_fu_1938_p3;

assign tmp_25_fu_1223_p4 = {{tmp_25_fu_1223_p1[23:8]}};

assign tmp_26_fu_1266_p1 = grp_fu_1946_p3;

assign tmp_26_fu_1266_p4 = {{tmp_26_fu_1266_p1[23:8]}};

assign tmp_27_fu_1307_p1 = grp_fu_1954_p3;

assign tmp_27_fu_1307_p4 = {{tmp_27_fu_1307_p1[23:8]}};

assign tmp_28_fu_1348_p1 = grp_fu_1962_p3;

assign tmp_28_fu_1348_p4 = {{tmp_28_fu_1348_p1[23:8]}};

assign tmp_29_fu_1389_p1 = grp_fu_1970_p3;

assign tmp_29_fu_1389_p4 = {{tmp_29_fu_1389_p1[23:8]}};

assign tmp_30_fu_1432_p1 = grp_fu_1978_p3;

assign tmp_30_fu_1432_p4 = {{tmp_30_fu_1432_p1[23:8]}};

assign tmp_31_fu_1472_p1 = grp_fu_1986_p3;

assign tmp_31_fu_1472_p4 = {{tmp_31_fu_1472_p1[23:8]}};

assign tmp_32_fu_1493_p1 = grp_fu_1994_p3;

assign tmp_32_fu_1493_p4 = {{tmp_32_fu_1493_p1[23:8]}};

assign tmp_33_fu_1513_p1 = grp_fu_2002_p3;

assign tmp_33_fu_1513_p4 = {{tmp_33_fu_1513_p1[23:8]}};

assign tmp_34_fu_1534_p1 = grp_fu_2010_p3;

assign tmp_34_fu_1534_p4 = {{tmp_34_fu_1534_p1[23:8]}};

assign tmp_35_fu_1554_p1 = grp_fu_2018_p3;

assign tmp_35_fu_1554_p4 = {{tmp_35_fu_1554_p1[23:8]}};

assign tmp_36_fu_1575_p1 = grp_fu_2026_p3;

assign tmp_36_fu_1575_p4 = {{tmp_36_fu_1575_p1[23:8]}};

assign tmp_37_fu_1595_p1 = grp_fu_2034_p3;

assign tmp_37_fu_1595_p4 = {{tmp_37_fu_1595_p1[23:8]}};

assign tmp_38_fu_1615_p1 = grp_fu_2042_p3;

assign tmp_38_fu_1615_p4 = {{tmp_38_fu_1615_p1[23:8]}};

assign tmp_39_fu_1635_p1 = grp_fu_2050_p3;

assign tmp_39_fu_1635_p4 = {{tmp_39_fu_1635_p1[23:8]}};

assign tmp_40_fu_1656_p1 = grp_fu_2058_p3;

assign tmp_40_fu_1656_p4 = {{tmp_40_fu_1656_p1[23:8]}};

assign tmp_41_fu_1676_p1 = grp_fu_2066_p3;

assign tmp_41_fu_1676_p4 = {{tmp_41_fu_1676_p1[23:8]}};

assign tmp_42_fu_1696_p1 = grp_fu_2074_p3;

assign tmp_42_fu_1696_p4 = {{tmp_42_fu_1696_p1[23:8]}};

assign tmp_43_fu_1716_p1 = grp_fu_2082_p3;

assign tmp_43_fu_1716_p4 = {{tmp_43_fu_1716_p1[23:8]}};

assign tmp_44_fu_1736_p1 = grp_fu_2090_p3;

assign tmp_44_fu_1736_p4 = {{tmp_44_fu_1736_p1[23:8]}};

assign tmp_45_fu_1756_p1 = grp_fu_2098_p3;

assign tmp_45_fu_1756_p4 = {{tmp_45_fu_1756_p1[23:8]}};

assign tmp_46_fu_1776_p1 = grp_fu_2106_p3;

assign tmp_46_fu_1776_p4 = {{tmp_46_fu_1776_p1[23:8]}};

assign tmp_47_fu_1796_p1 = grp_fu_2114_p3;

assign tmp_47_fu_1796_p4 = {{tmp_47_fu_1796_p1[23:8]}};

assign tmp_48_fu_1813_p1 = grp_fu_2122_p3;

assign tmp_48_fu_1813_p4 = {{tmp_48_fu_1813_p1[23:8]}};

assign tmp_fu_1873_p3 = add_ln11_1_fu_1867_p2[32'd16];

assign zext_ln11_fu_1835_p1 = add_ln11_fu_1830_p2;

assign zext_ln5_1_fu_844_p1 = ap_sig_allocacmp_i_2;

assign zext_ln5_fu_1840_p1 = i_2_reg_2305_pp0_iter1_reg;

assign zext_ln9_10_fu_1042_p1 = add_ln9_18_fu_1037_p2;

assign zext_ln9_11_fu_1052_p1 = add_ln9_20_fu_1047_p2;

assign zext_ln9_12_fu_1083_p1 = add_ln9_22_fu_1078_p2;

assign zext_ln9_13_cast_fu_1088_p3 = {{9'd330}, {i_2_reg_2305}};

assign zext_ln9_13_fu_1095_p1 = zext_ln9_13_cast_fu_1088_p3;

assign zext_ln9_14_fu_1126_p1 = add_ln9_25_fu_1121_p2;

assign zext_ln9_15_fu_1136_p1 = add_ln9_27_fu_1131_p2;

assign zext_ln9_16_fu_1167_p1 = add_ln9_29_fu_1162_p2;

assign zext_ln9_17_fu_1177_p1 = add_ln9_31_fu_1172_p2;

assign zext_ln9_18_fu_1208_p1 = add_ln9_33_fu_1203_p2;

assign zext_ln9_19_fu_1218_p1 = add_ln9_35_fu_1213_p2;

assign zext_ln9_1_fu_865_p1 = add_ln9_1_fu_859_p2;

assign zext_ln9_20_fu_1249_p1 = add_ln9_37_fu_1244_p2;

assign zext_ln9_21_cast_fu_1254_p3 = {{9'd335}, {i_2_reg_2305}};

assign zext_ln9_21_fu_1261_p1 = zext_ln9_21_cast_fu_1254_p3;

assign zext_ln9_22_fu_1292_p1 = add_ln9_40_fu_1287_p2;

assign zext_ln9_23_fu_1302_p1 = add_ln9_42_fu_1297_p2;

assign zext_ln9_24_fu_1333_p1 = add_ln9_44_fu_1328_p2;

assign zext_ln9_25_fu_1343_p1 = add_ln9_46_fu_1338_p2;

assign zext_ln9_26_fu_1374_p1 = add_ln9_48_fu_1369_p2;

assign zext_ln9_27_fu_1384_p1 = add_ln9_50_fu_1379_p2;

assign zext_ln9_28_fu_1415_p1 = add_ln9_52_fu_1410_p2;

assign zext_ln9_29_cast_fu_1420_p3 = {{9'd340}, {i_2_reg_2305}};

assign zext_ln9_29_fu_1427_p1 = zext_ln9_29_cast_fu_1420_p3;

assign zext_ln9_2_fu_903_p1 = add_ln9_3_fu_898_p2;

assign zext_ln9_30_fu_1457_p1 = add_ln9_55_fu_1452_p2;

assign zext_ln9_31_fu_1467_p1 = add_ln9_57_fu_1462_p2;

assign zext_ln9_3_fu_913_p1 = add_ln9_5_fu_908_p2;

assign zext_ln9_4_fu_927_p1 = add_ln9_7_fu_922_p2;

assign zext_ln9_5_cast_fu_932_p3 = {{9'd325}, {i_2_reg_2305}};

assign zext_ln9_5_fu_939_p1 = zext_ln9_5_cast_fu_932_p3;

assign zext_ln9_6_fu_960_p1 = add_ln9_10_fu_955_p2;

assign zext_ln9_7_fu_970_p1 = add_ln9_12_fu_965_p2;

assign zext_ln9_8_fu_1001_p1 = add_ln9_14_fu_996_p2;

assign zext_ln9_9_fu_1011_p1 = add_ln9_16_fu_1006_p2;

assign zext_ln9_fu_854_p1 = add_ln9_fu_848_p2;

always @ (posedge ap_clk) begin
    zext_ln5_1_reg_2318[13:5] <= 9'b000000000;
    zext_ln5_1_reg_2318_pp0_iter1_reg[13:5] <= 9'b000000000;
end

endmodule //CNN_CNN_Pipeline_loop_for_a_Dense_0
