// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_a_Dense_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Weights_address0,
        Weights_ce0,
        Weights_q0,
        Weights_address1,
        Weights_ce1,
        Weights_q1,
        sext_ln21,
        sext_ln21_1,
        sext_ln21_2,
        sext_ln21_3,
        sext_ln21_4,
        sext_ln21_5,
        sext_ln21_6,
        sext_ln21_7,
        sext_ln21_8,
        sext_ln21_9,
        sext_ln21_10,
        sext_ln21_11,
        sext_ln21_12,
        sext_ln21_13,
        sext_ln21_14,
        sext_ln21_15,
        sext_ln21_16,
        sext_ln21_17,
        sext_ln21_18,
        sext_ln21_19,
        out_Dense_address0,
        out_Dense_ce0,
        out_Dense_we0,
        out_Dense_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 11'd1;
parameter    ap_ST_fsm_pp0_stage1 = 11'd2;
parameter    ap_ST_fsm_pp0_stage2 = 11'd4;
parameter    ap_ST_fsm_pp0_stage3 = 11'd8;
parameter    ap_ST_fsm_pp0_stage4 = 11'd16;
parameter    ap_ST_fsm_pp0_stage5 = 11'd32;
parameter    ap_ST_fsm_pp0_stage6 = 11'd64;
parameter    ap_ST_fsm_pp0_stage7 = 11'd128;
parameter    ap_ST_fsm_pp0_stage8 = 11'd256;
parameter    ap_ST_fsm_pp0_stage9 = 11'd512;
parameter    ap_ST_fsm_pp0_stage10 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] Weights_address0;
output   Weights_ce0;
input  [15:0] Weights_q0;
output  [13:0] Weights_address1;
output   Weights_ce1;
input  [15:0] Weights_q1;
input  [15:0] sext_ln21;
input  [15:0] sext_ln21_1;
input  [15:0] sext_ln21_2;
input  [15:0] sext_ln21_3;
input  [15:0] sext_ln21_4;
input  [15:0] sext_ln21_5;
input  [15:0] sext_ln21_6;
input  [15:0] sext_ln21_7;
input  [15:0] sext_ln21_8;
input  [15:0] sext_ln21_9;
input  [15:0] sext_ln21_10;
input  [15:0] sext_ln21_11;
input  [15:0] sext_ln21_12;
input  [15:0] sext_ln21_13;
input  [15:0] sext_ln21_14;
input  [15:0] sext_ln21_15;
input  [15:0] sext_ln21_16;
input  [15:0] sext_ln21_17;
input  [15:0] sext_ln21_18;
input  [15:0] sext_ln21_19;
output  [2:0] out_Dense_address0;
output   out_Dense_ce0;
output   out_Dense_we0;
output  [15:0] out_Dense_d0;

reg ap_idle;
reg[13:0] Weights_address0;
reg Weights_ce0;
reg[13:0] Weights_address1;
reg Weights_ce1;
reg out_Dense_ce0;
reg out_Dense_we0;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_subdone;
reg   [0:0] icmp_ln17_reg_1479;
reg    ap_condition_exit_pp0_iter0_stage10;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg  signed [15:0] reg_444;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
reg  signed [15:0] reg_449;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_11001;
reg  signed [15:0] reg_454;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
reg  signed [15:0] reg_459;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_11001;
wire  signed [23:0] sext_ln21_19_cast_fu_464_p1;
reg  signed [23:0] sext_ln21_19_cast_reg_1372;
wire    ap_block_pp0_stage0_11001;
wire  signed [23:0] sext_ln21_18_cast_fu_468_p1;
reg  signed [23:0] sext_ln21_18_cast_reg_1377;
wire  signed [23:0] sext_ln21_17_cast_fu_472_p1;
reg  signed [23:0] sext_ln21_17_cast_reg_1382;
wire  signed [23:0] sext_ln21_16_cast_fu_476_p1;
reg  signed [23:0] sext_ln21_16_cast_reg_1387;
wire  signed [23:0] sext_ln21_15_cast_fu_480_p1;
reg  signed [23:0] sext_ln21_15_cast_reg_1392;
wire  signed [23:0] sext_ln21_14_cast_fu_484_p1;
reg  signed [23:0] sext_ln21_14_cast_reg_1397;
wire  signed [23:0] sext_ln21_13_cast_fu_488_p1;
reg  signed [23:0] sext_ln21_13_cast_reg_1402;
wire  signed [23:0] sext_ln21_12_cast_fu_492_p1;
reg  signed [23:0] sext_ln21_12_cast_reg_1407;
wire  signed [23:0] sext_ln21_11_cast_fu_496_p1;
reg  signed [23:0] sext_ln21_11_cast_reg_1412;
wire  signed [23:0] sext_ln21_10_cast_fu_500_p1;
reg  signed [23:0] sext_ln21_10_cast_reg_1417;
wire  signed [23:0] sext_ln21_9_cast_fu_504_p1;
reg  signed [23:0] sext_ln21_9_cast_reg_1422;
wire  signed [23:0] sext_ln21_8_cast_fu_508_p1;
reg  signed [23:0] sext_ln21_8_cast_reg_1427;
wire  signed [23:0] sext_ln21_7_cast_fu_512_p1;
reg  signed [23:0] sext_ln21_7_cast_reg_1432;
wire  signed [23:0] sext_ln21_6_cast_fu_516_p1;
reg  signed [23:0] sext_ln21_6_cast_reg_1437;
wire  signed [23:0] sext_ln21_5_cast_fu_520_p1;
reg  signed [23:0] sext_ln21_5_cast_reg_1442;
wire  signed [23:0] sext_ln21_4_cast_fu_524_p1;
reg  signed [23:0] sext_ln21_4_cast_reg_1447;
wire  signed [23:0] sext_ln21_3_cast_fu_528_p1;
reg  signed [23:0] sext_ln21_3_cast_reg_1452;
wire  signed [23:0] sext_ln21_2_cast_fu_532_p1;
reg  signed [23:0] sext_ln21_2_cast_reg_1457;
wire  signed [23:0] sext_ln21_1_cast_fu_536_p1;
reg  signed [23:0] sext_ln21_1_cast_reg_1462;
wire  signed [23:0] sext_ln21_cast_fu_540_p1;
reg  signed [23:0] sext_ln21_cast_reg_1467;
reg   [2:0] i_1_reg_1472;
reg   [2:0] i_1_reg_1472_pp0_iter1_reg;
wire   [0:0] icmp_ln17_fu_552_p2;
wire   [13:0] zext_ln17_1_fu_564_p1;
reg   [13:0] zext_ln17_1_reg_1483;
reg   [13:0] zext_ln17_1_reg_1483_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] tmp_s_reg_1519;
reg  signed [15:0] Weights_load_11_reg_1619;
reg  signed [15:0] Weights_load_13_reg_1644;
reg  signed [15:0] Weights_load_15_reg_1669;
reg  signed [15:0] Weights_load_17_reg_1694;
wire    ap_block_pp0_stage10_11001;
reg  signed [15:0] Weights_load_18_reg_1719;
reg  signed [15:0] Weights_load_19_reg_1724;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln21_fu_576_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln21_1_fu_587_p1;
wire   [63:0] zext_ln21_2_fu_625_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln21_3_fu_635_p1;
wire   [63:0] zext_ln21_4_fu_649_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln21_5_fu_659_p1;
wire   [63:0] zext_ln21_6_fu_680_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln21_7_fu_690_p1;
wire   [63:0] zext_ln21_8_fu_723_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln21_9_fu_733_p1;
wire   [63:0] zext_ln21_10_fu_764_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln21_11_fu_774_p1;
wire   [63:0] zext_ln21_12_fu_805_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln21_13_fu_815_p1;
wire   [63:0] zext_ln21_14_fu_846_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln21_15_fu_856_p1;
wire   [63:0] zext_ln21_16_fu_889_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln21_17_fu_899_p1;
wire   [63:0] zext_ln21_18_fu_930_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln21_19_fu_940_p1;
wire   [63:0] zext_ln23_fu_1188_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln17_fu_1193_p1;
reg   [2:0] i_fu_130;
wire   [2:0] add_ln17_fu_558_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_1;
wire   [13:0] zext_ln21_cast_fu_568_p3;
wire   [13:0] add_ln21_fu_581_p2;
wire  signed [15:0] mul_ln21_fu_601_p1;
wire   [23:0] mul_ln21_fu_601_p2;
wire   [13:0] add_ln21_2_fu_620_p2;
wire   [13:0] add_ln21_4_fu_630_p2;
wire   [13:0] add_ln21_6_fu_644_p2;
wire   [13:0] add_ln21_8_fu_654_p2;
wire   [13:0] add_ln21_10_fu_675_p2;
wire   [13:0] add_ln21_12_fu_685_p2;
wire  signed [23:0] tmp_1_fu_695_p1;
wire   [23:0] grp_fu_1213_p3;
wire   [15:0] tmp_1_fu_695_p4;
wire   [13:0] zext_ln21_8_cast_fu_716_p3;
wire   [13:0] add_ln21_15_fu_728_p2;
wire  signed [23:0] tmp_2_fu_738_p1;
wire   [23:0] grp_fu_1221_p3;
wire   [15:0] tmp_2_fu_738_p4;
wire   [13:0] add_ln21_17_fu_759_p2;
wire   [13:0] add_ln21_19_fu_769_p2;
wire  signed [23:0] tmp_3_fu_779_p1;
wire   [23:0] grp_fu_1229_p3;
wire   [15:0] tmp_3_fu_779_p4;
wire   [13:0] add_ln21_21_fu_800_p2;
wire   [13:0] add_ln21_23_fu_810_p2;
wire  signed [23:0] tmp_4_fu_820_p1;
wire   [23:0] grp_fu_1237_p3;
wire   [15:0] tmp_4_fu_820_p4;
wire   [13:0] add_ln21_25_fu_841_p2;
wire   [13:0] add_ln21_27_fu_851_p2;
wire  signed [23:0] tmp_5_fu_861_p1;
wire   [23:0] grp_fu_1245_p3;
wire   [15:0] tmp_5_fu_861_p4;
wire   [13:0] zext_ln21_16_cast_fu_882_p3;
wire   [13:0] add_ln21_30_fu_894_p2;
wire  signed [23:0] tmp_6_fu_904_p1;
wire   [23:0] grp_fu_1253_p3;
wire   [15:0] tmp_6_fu_904_p4;
wire   [13:0] add_ln21_32_fu_925_p2;
wire   [13:0] add_ln21_34_fu_935_p2;
wire  signed [23:0] tmp_7_fu_945_p1;
wire   [23:0] grp_fu_1261_p3;
wire   [15:0] tmp_7_fu_945_p4;
wire  signed [23:0] tmp_8_fu_966_p1;
wire   [23:0] grp_fu_1269_p3;
wire   [15:0] tmp_8_fu_966_p4;
wire  signed [23:0] tmp_9_fu_986_p1;
wire   [23:0] grp_fu_1277_p3;
wire   [15:0] tmp_9_fu_986_p4;
wire  signed [23:0] tmp_10_fu_1007_p1;
wire   [23:0] grp_fu_1285_p3;
wire   [15:0] tmp_10_fu_1007_p4;
wire  signed [23:0] tmp_11_fu_1027_p1;
wire   [23:0] grp_fu_1293_p3;
wire   [15:0] tmp_11_fu_1027_p4;
wire  signed [23:0] tmp_12_fu_1048_p1;
wire   [23:0] grp_fu_1301_p3;
wire   [15:0] tmp_12_fu_1048_p4;
wire  signed [23:0] tmp_13_fu_1068_p1;
wire   [23:0] grp_fu_1309_p3;
wire   [15:0] tmp_13_fu_1068_p4;
wire  signed [23:0] tmp_14_fu_1089_p1;
wire   [23:0] grp_fu_1317_p3;
wire   [15:0] tmp_14_fu_1089_p4;
wire  signed [23:0] tmp_15_fu_1109_p1;
wire   [23:0] grp_fu_1325_p3;
wire   [15:0] tmp_15_fu_1109_p4;
wire  signed [23:0] tmp_16_fu_1129_p1;
wire   [23:0] grp_fu_1333_p3;
wire   [15:0] tmp_16_fu_1129_p4;
wire  signed [23:0] tmp_17_fu_1149_p1;
wire   [23:0] grp_fu_1341_p3;
wire   [15:0] tmp_17_fu_1149_p4;
wire  signed [23:0] tmp_18_fu_1166_p1;
wire   [23:0] grp_fu_1349_p3;
wire   [15:0] tmp_18_fu_1166_p4;
wire   [13:0] add_ln23_fu_1183_p2;
wire  signed [23:0] s_fu_1197_p1;
wire   [23:0] grp_fu_1357_p3;
wire   [15:0] s_fu_1197_p4;
wire  signed [15:0] grp_fu_1213_p1;
wire   [23:0] grp_fu_1213_p2;
wire  signed [15:0] grp_fu_1221_p1;
wire   [23:0] grp_fu_1221_p2;
wire  signed [15:0] grp_fu_1229_p1;
wire   [23:0] grp_fu_1229_p2;
wire  signed [15:0] grp_fu_1237_p1;
wire   [23:0] grp_fu_1237_p2;
wire  signed [15:0] grp_fu_1245_p1;
wire   [23:0] grp_fu_1245_p2;
wire  signed [15:0] grp_fu_1253_p1;
wire   [23:0] grp_fu_1253_p2;
wire  signed [15:0] grp_fu_1261_p1;
wire   [23:0] grp_fu_1261_p2;
wire  signed [15:0] grp_fu_1269_p1;
wire   [23:0] grp_fu_1269_p2;
wire  signed [15:0] grp_fu_1277_p1;
wire   [23:0] grp_fu_1277_p2;
wire  signed [15:0] grp_fu_1285_p1;
wire   [23:0] grp_fu_1285_p2;
wire  signed [15:0] grp_fu_1293_p1;
wire   [23:0] grp_fu_1293_p2;
wire  signed [15:0] grp_fu_1301_p1;
wire   [23:0] grp_fu_1301_p2;
wire  signed [15:0] grp_fu_1309_p1;
wire   [23:0] grp_fu_1309_p2;
wire  signed [15:0] grp_fu_1317_p1;
wire   [23:0] grp_fu_1317_p2;
wire  signed [15:0] grp_fu_1325_p1;
wire   [23:0] grp_fu_1325_p2;
wire  signed [15:0] grp_fu_1333_p1;
wire   [23:0] grp_fu_1333_p2;
wire  signed [15:0] grp_fu_1341_p1;
wire   [23:0] grp_fu_1341_p2;
wire  signed [15:0] grp_fu_1349_p1;
wire   [23:0] grp_fu_1349_p2;
wire  signed [15:0] grp_fu_1357_p1;
wire   [23:0] grp_fu_1357_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_130 = 3'd0;
#0 ap_done_reg = 1'b0;
end

CNN_mul_16s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_16s_16s_24_1_1_U290(
    .din0(Weights_q1),
    .din1(mul_ln21_fu_601_p1),
    .dout(mul_ln21_fu_601_p2)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U291(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_q0),
    .din1(grp_fu_1213_p1),
    .din2(grp_fu_1213_p2),
    .ce(1'b1),
    .dout(grp_fu_1213_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U292(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_q1),
    .din1(grp_fu_1221_p1),
    .din2(grp_fu_1221_p2),
    .ce(1'b1),
    .dout(grp_fu_1221_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U293(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_444),
    .din1(grp_fu_1229_p1),
    .din2(grp_fu_1229_p2),
    .ce(1'b1),
    .dout(grp_fu_1229_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U294(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_444),
    .din1(grp_fu_1237_p1),
    .din2(grp_fu_1237_p2),
    .ce(1'b1),
    .dout(grp_fu_1237_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U295(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_449),
    .din1(grp_fu_1245_p1),
    .din2(grp_fu_1245_p2),
    .ce(1'b1),
    .dout(grp_fu_1245_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U296(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_444),
    .din1(grp_fu_1253_p1),
    .din2(grp_fu_1253_p2),
    .ce(1'b1),
    .dout(grp_fu_1253_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U297(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_454),
    .din1(grp_fu_1261_p1),
    .din2(grp_fu_1261_p2),
    .ce(1'b1),
    .dout(grp_fu_1261_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U298(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_449),
    .din1(grp_fu_1269_p1),
    .din2(grp_fu_1269_p2),
    .ce(1'b1),
    .dout(grp_fu_1269_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U299(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_459),
    .din1(grp_fu_1277_p1),
    .din2(grp_fu_1277_p2),
    .ce(1'b1),
    .dout(grp_fu_1277_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U300(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_444),
    .din1(grp_fu_1285_p1),
    .din2(grp_fu_1285_p2),
    .ce(1'b1),
    .dout(grp_fu_1285_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U301(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_11_reg_1619),
    .din1(grp_fu_1293_p1),
    .din2(grp_fu_1293_p2),
    .ce(1'b1),
    .dout(grp_fu_1293_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U302(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_454),
    .din1(grp_fu_1301_p1),
    .din2(grp_fu_1301_p2),
    .ce(1'b1),
    .dout(grp_fu_1301_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U303(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_13_reg_1644),
    .din1(grp_fu_1309_p1),
    .din2(grp_fu_1309_p2),
    .ce(1'b1),
    .dout(grp_fu_1309_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U304(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_449),
    .din1(grp_fu_1317_p1),
    .din2(grp_fu_1317_p2),
    .ce(1'b1),
    .dout(grp_fu_1317_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U305(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_15_reg_1669),
    .din1(grp_fu_1325_p1),
    .din2(grp_fu_1325_p2),
    .ce(1'b1),
    .dout(grp_fu_1325_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U306(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_459),
    .din1(grp_fu_1333_p1),
    .din2(grp_fu_1333_p2),
    .ce(1'b1),
    .dout(grp_fu_1333_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U307(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_17_reg_1694),
    .din1(grp_fu_1341_p1),
    .din2(grp_fu_1341_p2),
    .ce(1'b1),
    .dout(grp_fu_1341_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U308(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_18_reg_1719),
    .din1(grp_fu_1349_p1),
    .din2(grp_fu_1349_p2),
    .ce(1'b1),
    .dout(grp_fu_1349_p3)
);

CNN_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U309(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Weights_load_19_reg_1724),
    .din1(grp_fu_1357_p1),
    .din2(grp_fu_1357_p2),
    .ce(1'b1),
    .dout(grp_fu_1357_p3)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage10),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage10)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln17_fu_552_p2 == 1'd0))) begin
            i_fu_130 <= add_ln17_fu_558_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_130 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_444 <= Weights_q1;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_444 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_449 <= Weights_q1;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_449 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            reg_454 <= Weights_q1;
        end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            reg_454 <= Weights_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            reg_459 <= Weights_q1;
        end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            reg_459 <= Weights_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        Weights_load_11_reg_1619 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        Weights_load_13_reg_1644 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        Weights_load_15_reg_1669 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        Weights_load_17_reg_1694 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        Weights_load_18_reg_1719 <= Weights_q1;
        Weights_load_19_reg_1724 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_1472 <= ap_sig_allocacmp_i_1;
        i_1_reg_1472_pp0_iter1_reg <= i_1_reg_1472;
        icmp_ln17_reg_1479 <= icmp_ln17_fu_552_p2;
        sext_ln21_10_cast_reg_1417 <= sext_ln21_10_cast_fu_500_p1;
        sext_ln21_11_cast_reg_1412 <= sext_ln21_11_cast_fu_496_p1;
        sext_ln21_12_cast_reg_1407 <= sext_ln21_12_cast_fu_492_p1;
        sext_ln21_13_cast_reg_1402 <= sext_ln21_13_cast_fu_488_p1;
        sext_ln21_14_cast_reg_1397 <= sext_ln21_14_cast_fu_484_p1;
        sext_ln21_15_cast_reg_1392 <= sext_ln21_15_cast_fu_480_p1;
        sext_ln21_16_cast_reg_1387 <= sext_ln21_16_cast_fu_476_p1;
        sext_ln21_17_cast_reg_1382 <= sext_ln21_17_cast_fu_472_p1;
        sext_ln21_18_cast_reg_1377 <= sext_ln21_18_cast_fu_468_p1;
        sext_ln21_19_cast_reg_1372 <= sext_ln21_19_cast_fu_464_p1;
        sext_ln21_1_cast_reg_1462 <= sext_ln21_1_cast_fu_536_p1;
        sext_ln21_2_cast_reg_1457 <= sext_ln21_2_cast_fu_532_p1;
        sext_ln21_3_cast_reg_1452 <= sext_ln21_3_cast_fu_528_p1;
        sext_ln21_4_cast_reg_1447 <= sext_ln21_4_cast_fu_524_p1;
        sext_ln21_5_cast_reg_1442 <= sext_ln21_5_cast_fu_520_p1;
        sext_ln21_6_cast_reg_1437 <= sext_ln21_6_cast_fu_516_p1;
        sext_ln21_7_cast_reg_1432 <= sext_ln21_7_cast_fu_512_p1;
        sext_ln21_8_cast_reg_1427 <= sext_ln21_8_cast_fu_508_p1;
        sext_ln21_9_cast_reg_1422 <= sext_ln21_9_cast_fu_504_p1;
        sext_ln21_cast_reg_1467 <= sext_ln21_cast_fu_540_p1;
        zext_ln17_1_reg_1483[2 : 0] <= zext_ln17_1_fu_564_p1[2 : 0];
        zext_ln17_1_reg_1483_pp0_iter1_reg[2 : 0] <= zext_ln17_1_reg_1483[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_s_reg_1519 <= {{mul_ln21_fu_601_p2[23:8]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        Weights_address0 = zext_ln23_fu_1188_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        Weights_address0 = zext_ln21_19_fu_940_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        Weights_address0 = zext_ln21_17_fu_899_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        Weights_address0 = zext_ln21_15_fu_856_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        Weights_address0 = zext_ln21_13_fu_815_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        Weights_address0 = zext_ln21_11_fu_774_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        Weights_address0 = zext_ln21_9_fu_733_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        Weights_address0 = zext_ln21_7_fu_690_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Weights_address0 = zext_ln21_5_fu_659_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Weights_address0 = zext_ln21_3_fu_635_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Weights_address0 = zext_ln21_1_fu_587_p1;
    end else begin
        Weights_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            Weights_address1 = zext_ln21_18_fu_930_p1;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            Weights_address1 = zext_ln21_16_fu_889_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            Weights_address1 = zext_ln21_14_fu_846_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            Weights_address1 = zext_ln21_12_fu_805_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            Weights_address1 = zext_ln21_10_fu_764_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            Weights_address1 = zext_ln21_8_fu_723_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            Weights_address1 = zext_ln21_6_fu_680_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            Weights_address1 = zext_ln21_4_fu_649_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Weights_address1 = zext_ln21_2_fu_625_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Weights_address1 = zext_ln21_fu_576_p1;
        end else begin
            Weights_address1 = 'bx;
        end
    end else begin
        Weights_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Weights_ce0 = 1'b1;
    end else begin
        Weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Weights_ce1 = 1'b1;
    end else begin
        Weights_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln17_reg_1479 == 1'd1) & (1'b0 == ap_block_pp0_stage10_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_condition_exit_pp0_iter0_stage10 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage10 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln17_reg_1479 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage10_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_Dense_ce0 = 1'b1;
    end else begin
        out_Dense_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_Dense_we0 = 1'b1;
    end else begin
        out_Dense_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_fu_558_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign add_ln21_10_fu_675_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd10990));

assign add_ln21_12_fu_685_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd10995));

assign add_ln21_15_fu_728_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11005));

assign add_ln21_17_fu_759_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11010));

assign add_ln21_19_fu_769_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11015));

assign add_ln21_21_fu_800_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11020));

assign add_ln21_23_fu_810_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11025));

assign add_ln21_25_fu_841_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11030));

assign add_ln21_27_fu_851_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11035));

assign add_ln21_2_fu_620_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd10970));

assign add_ln21_30_fu_894_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11045));

assign add_ln21_32_fu_925_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11050));

assign add_ln21_34_fu_935_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd11055));

assign add_ln21_4_fu_630_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd10975));

assign add_ln21_6_fu_644_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd10980));

assign add_ln21_8_fu_654_p2 = ($signed(zext_ln17_1_reg_1483) + $signed(14'd10985));

assign add_ln21_fu_581_p2 = ($signed(zext_ln17_1_fu_564_p1) + $signed(14'd10965));

assign add_ln23_fu_1183_p2 = ($signed(zext_ln17_1_reg_1483_pp0_iter1_reg) + $signed(14'd11060));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage10;

assign grp_fu_1213_p1 = sext_ln21_1_cast_reg_1462;

assign grp_fu_1213_p2 = {{tmp_s_reg_1519}, {8'd0}};

assign grp_fu_1221_p1 = sext_ln21_2_cast_reg_1457;

assign grp_fu_1221_p2 = {{tmp_1_fu_695_p4}, {8'd0}};

assign grp_fu_1229_p1 = sext_ln21_3_cast_reg_1452;

assign grp_fu_1229_p2 = {{tmp_2_fu_738_p4}, {8'd0}};

assign grp_fu_1237_p1 = sext_ln21_4_cast_reg_1447;

assign grp_fu_1237_p2 = {{tmp_3_fu_779_p4}, {8'd0}};

assign grp_fu_1245_p1 = sext_ln21_5_cast_reg_1442;

assign grp_fu_1245_p2 = {{tmp_4_fu_820_p4}, {8'd0}};

assign grp_fu_1253_p1 = sext_ln21_6_cast_reg_1437;

assign grp_fu_1253_p2 = {{tmp_5_fu_861_p4}, {8'd0}};

assign grp_fu_1261_p1 = sext_ln21_7_cast_reg_1432;

assign grp_fu_1261_p2 = {{tmp_6_fu_904_p4}, {8'd0}};

assign grp_fu_1269_p1 = sext_ln21_8_cast_reg_1427;

assign grp_fu_1269_p2 = {{tmp_7_fu_945_p4}, {8'd0}};

assign grp_fu_1277_p1 = sext_ln21_9_cast_reg_1422;

assign grp_fu_1277_p2 = {{tmp_8_fu_966_p4}, {8'd0}};

assign grp_fu_1285_p1 = sext_ln21_10_cast_reg_1417;

assign grp_fu_1285_p2 = {{tmp_9_fu_986_p4}, {8'd0}};

assign grp_fu_1293_p1 = sext_ln21_11_cast_reg_1412;

assign grp_fu_1293_p2 = {{tmp_10_fu_1007_p4}, {8'd0}};

assign grp_fu_1301_p1 = sext_ln21_12_cast_reg_1407;

assign grp_fu_1301_p2 = {{tmp_11_fu_1027_p4}, {8'd0}};

assign grp_fu_1309_p1 = sext_ln21_13_cast_reg_1402;

assign grp_fu_1309_p2 = {{tmp_12_fu_1048_p4}, {8'd0}};

assign grp_fu_1317_p1 = sext_ln21_14_cast_reg_1397;

assign grp_fu_1317_p2 = {{tmp_13_fu_1068_p4}, {8'd0}};

assign grp_fu_1325_p1 = sext_ln21_15_cast_reg_1392;

assign grp_fu_1325_p2 = {{tmp_14_fu_1089_p4}, {8'd0}};

assign grp_fu_1333_p1 = sext_ln21_16_cast_reg_1387;

assign grp_fu_1333_p2 = {{tmp_15_fu_1109_p4}, {8'd0}};

assign grp_fu_1341_p1 = sext_ln21_17_cast_reg_1382;

assign grp_fu_1341_p2 = {{tmp_16_fu_1129_p4}, {8'd0}};

assign grp_fu_1349_p1 = sext_ln21_18_cast_reg_1377;

assign grp_fu_1349_p2 = {{tmp_17_fu_1149_p4}, {8'd0}};

assign grp_fu_1357_p1 = sext_ln21_19_cast_reg_1372;

assign grp_fu_1357_p2 = {{tmp_18_fu_1166_p4}, {8'd0}};

assign icmp_ln17_fu_552_p2 = ((ap_sig_allocacmp_i_1 == 3'd5) ? 1'b1 : 1'b0);

assign mul_ln21_fu_601_p1 = sext_ln21_cast_reg_1467;

assign out_Dense_address0 = zext_ln17_fu_1193_p1;

assign out_Dense_d0 = (Weights_q0 + s_fu_1197_p4);

assign s_fu_1197_p1 = grp_fu_1357_p3;

assign s_fu_1197_p4 = {{s_fu_1197_p1[23:8]}};

assign sext_ln21_10_cast_fu_500_p1 = $signed(sext_ln21_10);

assign sext_ln21_11_cast_fu_496_p1 = $signed(sext_ln21_11);

assign sext_ln21_12_cast_fu_492_p1 = $signed(sext_ln21_12);

assign sext_ln21_13_cast_fu_488_p1 = $signed(sext_ln21_13);

assign sext_ln21_14_cast_fu_484_p1 = $signed(sext_ln21_14);

assign sext_ln21_15_cast_fu_480_p1 = $signed(sext_ln21_15);

assign sext_ln21_16_cast_fu_476_p1 = $signed(sext_ln21_16);

assign sext_ln21_17_cast_fu_472_p1 = $signed(sext_ln21_17);

assign sext_ln21_18_cast_fu_468_p1 = $signed(sext_ln21_18);

assign sext_ln21_19_cast_fu_464_p1 = $signed(sext_ln21_19);

assign sext_ln21_1_cast_fu_536_p1 = $signed(sext_ln21_1);

assign sext_ln21_2_cast_fu_532_p1 = $signed(sext_ln21_2);

assign sext_ln21_3_cast_fu_528_p1 = $signed(sext_ln21_3);

assign sext_ln21_4_cast_fu_524_p1 = $signed(sext_ln21_4);

assign sext_ln21_5_cast_fu_520_p1 = $signed(sext_ln21_5);

assign sext_ln21_6_cast_fu_516_p1 = $signed(sext_ln21_6);

assign sext_ln21_7_cast_fu_512_p1 = $signed(sext_ln21_7);

assign sext_ln21_8_cast_fu_508_p1 = $signed(sext_ln21_8);

assign sext_ln21_9_cast_fu_504_p1 = $signed(sext_ln21_9);

assign sext_ln21_cast_fu_540_p1 = $signed(sext_ln21);

assign tmp_10_fu_1007_p1 = grp_fu_1285_p3;

assign tmp_10_fu_1007_p4 = {{tmp_10_fu_1007_p1[23:8]}};

assign tmp_11_fu_1027_p1 = grp_fu_1293_p3;

assign tmp_11_fu_1027_p4 = {{tmp_11_fu_1027_p1[23:8]}};

assign tmp_12_fu_1048_p1 = grp_fu_1301_p3;

assign tmp_12_fu_1048_p4 = {{tmp_12_fu_1048_p1[23:8]}};

assign tmp_13_fu_1068_p1 = grp_fu_1309_p3;

assign tmp_13_fu_1068_p4 = {{tmp_13_fu_1068_p1[23:8]}};

assign tmp_14_fu_1089_p1 = grp_fu_1317_p3;

assign tmp_14_fu_1089_p4 = {{tmp_14_fu_1089_p1[23:8]}};

assign tmp_15_fu_1109_p1 = grp_fu_1325_p3;

assign tmp_15_fu_1109_p4 = {{tmp_15_fu_1109_p1[23:8]}};

assign tmp_16_fu_1129_p1 = grp_fu_1333_p3;

assign tmp_16_fu_1129_p4 = {{tmp_16_fu_1129_p1[23:8]}};

assign tmp_17_fu_1149_p1 = grp_fu_1341_p3;

assign tmp_17_fu_1149_p4 = {{tmp_17_fu_1149_p1[23:8]}};

assign tmp_18_fu_1166_p1 = grp_fu_1349_p3;

assign tmp_18_fu_1166_p4 = {{tmp_18_fu_1166_p1[23:8]}};

assign tmp_1_fu_695_p1 = grp_fu_1213_p3;

assign tmp_1_fu_695_p4 = {{tmp_1_fu_695_p1[23:8]}};

assign tmp_2_fu_738_p1 = grp_fu_1221_p3;

assign tmp_2_fu_738_p4 = {{tmp_2_fu_738_p1[23:8]}};

assign tmp_3_fu_779_p1 = grp_fu_1229_p3;

assign tmp_3_fu_779_p4 = {{tmp_3_fu_779_p1[23:8]}};

assign tmp_4_fu_820_p1 = grp_fu_1237_p3;

assign tmp_4_fu_820_p4 = {{tmp_4_fu_820_p1[23:8]}};

assign tmp_5_fu_861_p1 = grp_fu_1245_p3;

assign tmp_5_fu_861_p4 = {{tmp_5_fu_861_p1[23:8]}};

assign tmp_6_fu_904_p1 = grp_fu_1253_p3;

assign tmp_6_fu_904_p4 = {{tmp_6_fu_904_p1[23:8]}};

assign tmp_7_fu_945_p1 = grp_fu_1261_p3;

assign tmp_7_fu_945_p4 = {{tmp_7_fu_945_p1[23:8]}};

assign tmp_8_fu_966_p1 = grp_fu_1269_p3;

assign tmp_8_fu_966_p4 = {{tmp_8_fu_966_p1[23:8]}};

assign tmp_9_fu_986_p1 = grp_fu_1277_p3;

assign tmp_9_fu_986_p4 = {{tmp_9_fu_986_p1[23:8]}};

assign zext_ln17_1_fu_564_p1 = ap_sig_allocacmp_i_1;

assign zext_ln17_fu_1193_p1 = i_1_reg_1472_pp0_iter1_reg;

assign zext_ln21_10_fu_764_p1 = add_ln21_17_fu_759_p2;

assign zext_ln21_11_fu_774_p1 = add_ln21_19_fu_769_p2;

assign zext_ln21_12_fu_805_p1 = add_ln21_21_fu_800_p2;

assign zext_ln21_13_fu_815_p1 = add_ln21_23_fu_810_p2;

assign zext_ln21_14_fu_846_p1 = add_ln21_25_fu_841_p2;

assign zext_ln21_15_fu_856_p1 = add_ln21_27_fu_851_p2;

assign zext_ln21_16_cast_fu_882_p3 = {{11'd1380}, {i_1_reg_1472}};

assign zext_ln21_16_fu_889_p1 = zext_ln21_16_cast_fu_882_p3;

assign zext_ln21_17_fu_899_p1 = add_ln21_30_fu_894_p2;

assign zext_ln21_18_fu_930_p1 = add_ln21_32_fu_925_p2;

assign zext_ln21_19_fu_940_p1 = add_ln21_34_fu_935_p2;

assign zext_ln21_1_fu_587_p1 = add_ln21_fu_581_p2;

assign zext_ln21_2_fu_625_p1 = add_ln21_2_fu_620_p2;

assign zext_ln21_3_fu_635_p1 = add_ln21_4_fu_630_p2;

assign zext_ln21_4_fu_649_p1 = add_ln21_6_fu_644_p2;

assign zext_ln21_5_fu_659_p1 = add_ln21_8_fu_654_p2;

assign zext_ln21_6_fu_680_p1 = add_ln21_10_fu_675_p2;

assign zext_ln21_7_fu_690_p1 = add_ln21_12_fu_685_p2;

assign zext_ln21_8_cast_fu_716_p3 = {{11'd1375}, {i_1_reg_1472}};

assign zext_ln21_8_fu_723_p1 = zext_ln21_8_cast_fu_716_p3;

assign zext_ln21_9_fu_733_p1 = add_ln21_15_fu_728_p2;

assign zext_ln21_cast_fu_568_p3 = {{11'd1370}, {ap_sig_allocacmp_i_1}};

assign zext_ln21_fu_576_p1 = zext_ln21_cast_fu_568_p3;

assign zext_ln23_fu_1188_p1 = add_ln23_fu_1183_p2;

always @ (posedge ap_clk) begin
    zext_ln17_1_reg_1483[13:3] <= 11'b00000000000;
    zext_ln17_1_reg_1483_pp0_iter1_reg[13:3] <= 11'b00000000000;
end

endmodule //CNN_CNN_Pipeline_loop_for_a_Dense_1
